class MotorModel {
  final List<String> brand;

  MotorModel({required this.brand});
}

final List<MotorModel> motormake = [
  MotorModel(brand: ['Aprilia']),
  MotorModel(brand: ['Bajaj']),
  MotorModel(brand: ['Beta']),
  MotorModel(brand: ['BSA']),
  MotorModel(brand: ['Benelli']),
  MotorModel(brand: ['BMW']),
  MotorModel(brand: ['CFMoto']),
  MotorModel(brand: ['Can-Am']),
  MotorModel(brand: ['Cagiva']),
  MotorModel(brand: ['Ducati']),
  MotorModel(brand: ['Euro Keeway']),
  MotorModel(brand: ['Gilera']),
  MotorModel(brand: ['Harley']),
  MotorModel(brand: ['Harley-Davidson']),
  MotorModel(brand: ['Haojue']),
  MotorModel(brand: ['Honda']),
  MotorModel(brand: ['Husqvarna']),
  MotorModel(brand: ['Indian Motorcycle']),
  MotorModel(brand: ['Italjet']),
  MotorModel(brand: ['Jianshe']),
  MotorModel(brand: ['Kawasaki']),
  MotorModel(brand: ['KTM']),
  MotorModel(brand: ['Kymco']),
  MotorModel(brand: ['Lifan']),
  MotorModel(brand: ['LML']),
  MotorModel(brand: ['Loncin']),
  MotorModel(brand: ['MCX']),
  MotorModel(brand: ['Moto Guzzi']),
  MotorModel(brand: ['Motorstar']),
  MotorModel(brand: ['Peugeot']),
  MotorModel(brand: ['PGO']),
  MotorModel(brand: ['Piaggio']),
  MotorModel(brand: ['PMR']),
  MotorModel(brand: ['MV Agusta']),
  MotorModel(brand: ['Norton']),
  MotorModel(brand: ['Royal Enfield']),
  MotorModel(brand: ['Rusi']),
  MotorModel(brand: ['Sinski']),
  MotorModel(brand: ['Skygo']),
  MotorModel(brand: ['Suzuki']),
  MotorModel(brand: ['Sym']),
  MotorModel(brand: ['Triumph']),
  MotorModel(brand: ['TVS']),
  MotorModel(brand: ['Vespa']),
  MotorModel(brand: ['Victory']),
  MotorModel(brand: ['Yamaha']),
  MotorModel(brand: ['Zero Motorcycles']),
  MotorModel(brand: ['Zongshen']),
];